version: "3.7"

services:
  backend:
    image: walletstash-dca:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - SEED_USERNAME=admin
      - SEED_PASSWORD=password
      - LOGS_DIR=/build/logs/
      - DB_DIR=/build/db/
    ports:
      - 3000:3000
    volumes:
      - ./db:/build/db
      - ./logs:/build/logs
