name: 'build-test'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server: # make sure build/ci work properly
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd server
      - run: npm install
      - run: npm run build
